### ISSUE TITLE
2-9-update data structure

### ISSUE THREAD

**Issue by marvinRoellecke** [marvinRoellecke/capstone-project#11]
## Value Proposition

**As a** developer 
**I want to** update the data structure 
**so that** the app has more useful data
​

## Description

```
{
  "id": 1,
  "title": "Sportanlage Mauritz-Lindenweg",
  "info": [
    {
      "sport": "basketball",
      "numberOfCourts": 2,
      "surface": "kunststoff"
    },
    {
      "sport": "beachvolleyball",
      "numberOfCourts": 3,
      "surface": "sand"
    },
    {
      "sport": "tischtennis",
      "numberOfCourts": 2,
      "surface": "beton"
    },
    {
      "sport": "speckbrett",
      "numberOfCourts": 2,
      "surface": "beton"
    }
  ],
  "address": {
    "street": "Mauritz-Lindenweg",
    "houseNumber": 93,
    "postcode": 48145,
    "city": "Münster"
  },
  "latitude": "51.779003",
  "longitude": "6.914183",
  "image": "/img/samplePics/basketball3.jpg",
  "infrastructure": {
    "lighting": "true",
    "wheelchair": "true"
  },
  "outdoor": "outdoor",
  "public": "public",
  "rating": 4.2,
}
```

## Acceptance Criteria

- [x] update data structure in database like in description above 
- [ ] min. 50 entries (as I want to have real data it takes more time than expected. Data will be added to the database from time to time)
- [ ] min. 5 different cities (same as above)
- [x] sport categories: basketball, volleyball, soccer, fitness, table tennis, watersport, dirt-park, other, ....

## Tasks

(for developers team)

- [x] update data structure as described
- [ ] collect data (real locations) (in progress)
- [x] create pull request
