### ISSUE TITLE
2-11_refactor

### ISSUE THREAD

**Issue by marvinRoellecke** [marvinRoellecke/capstone-project#13]
## Value Proposition

**As a** developer 
**I want to** refactor the code
**so that** the code is easier to read and understand.
​

## Description

some files got quite large over the time what make the code hard to read.
In order to ensure good intelligibility it is necessary  to review the code and look for possibilities for refactoring.

## Acceptance Criteria

- [x] functionality must not be impaired
- [x] clearly naming of functions, components, variables
- [x] no repeating code -> DRY principle

## Tasks

(for developers team)

- [ ] export sort functions in pages/index.js (will be deleted when sort/filter via database queries)
- [x] make react icons "stupid" components. change their style using props
- [x] FilterMenu.js: refactor to eliminate repeating code (form)
- [x] refactor styled components with equal properties
- [x] create pull request
