### ISSUE TITLE
2-12_filter and sort via database queries

### ISSUE THREAD

**Issue by marvinRoellecke** [marvinRoellecke/capstone-project#14]
## Value Proposition

**As a** developer 
**I want to** filter and sort data via database queries
**to be able** to have filter and sort function easier and better performing than with array methods
​

## Description

Use database queries to sort and filter data. This is currently realized with complex array methods.

## Acceptance Criteria

- [ ] filter data by multiple criteria (e.g. sport, city, rating, ...)
- [ ] sort data alphabetically and last added 
- [ ] filter and sort must work simultaneously 

## Tasks

(for developers team)

- [ ] add filter and .find method in GET request
- [ ] add sort method in GET request
- [ ] write function to modify url query string   
- [ ] delete legacy sort and filter function
- [ ] create pull request

**Comment by ufelgen** [comment]
sieht gut aus, würde ich sagen (obwohl ich ja großer Fan von Array-Methoden bin 🙃)
