### ISSUE TITLE
3-13_update details page with more information

### ISSUE THREAD

**Issue by marvinRoellecke** [marvinRoellecke/capstone-project#15]
## Value Proposition

**As a** user 

**I want to** see detailed information of a sport locations after clicked on list item

**to be able to** get more information about the place where I think about to go to

## Description

![3-13_new details page](https://user-images.githubusercontent.com/115343305/211286819-c5b3097a-cb07-4df7-a5ae-63968700f395.png)

## Acceptance Criteria

- [x] show additional information [sport, number of courts, court surface, lighting, wheelchair access, outdoor/indoor, public/private]
- [x] information is shown in boxes using text and symbols 

## Tasks

(for developers team)

- [x] update [details].js with additional information
- [x] use .map method to render multiple sport information (as reference see sketch with soccer and basketball)
- [x] sport/general information is aligned into grid or flexbox
- [x] create pull request

**Comment by NeeleWaehnke** [comment]
Hey Marvin, sehr gut beschriebene User Story :)
