### ISSUE TITLE
3-14_add map

### ISSUE THREAD

**Issue by marvinRoellecke** [marvinRoellecke/capstone-project#16]
## Value Proposition

**As a** user 

**I want to** look for a sport location on a map

**to be able to** to get a better overview where the places are

## Description

![3-14_add map](https://user-images.githubusercontent.com/115343305/211289526-ab475bb8-273d-4e69-8547-b1a7f391400c.png)

## Acceptance Criteria

- [ ] map that shows position of sport locations
- [ ] button on the navBar that routes to the map

## Tasks

(for developers team)

- [ ] install map api
- [ ] add button to navBar
- [ ] create pull request

**Comment by marvinRoellecke** [comment]
danke fürs drüberschauen :)
Die Koordinaten sind im jeweiligen Objekt der "Location" gespeichert.
