### ISSUE TITLE
3-15_show current position on map

### ISSUE THREAD

**Issue by marvinRoellecke** [marvinRoellecke/capstone-project#17]
## Value Proposition

**As a** user 

**I want to** see my current position on the map

**to be able to** to see where I am

## Description

![3-15_show current position map](https://user-images.githubusercontent.com/115343305/211290839-9ce3be14-fa03-4b02-8359-699e76a4de6f.png)

## Acceptance Criteria

- [x] map shows current position in addition to sports locations

## Tasks

(for developers team)

- [x] add feature to show current position
- [x] create pull request

**Comment by ufelgen** [comment]
Vorschlag: map shows current position in addition to sports locations

**Comment by marvinRoellecke** [comment]
das ist gut, danke
