### ISSUE TITLE
3-17_add multiple sports to one location

### ISSUE THREAD

**Issue by marvinRoellecke** [marvinRoellecke/capstone-project#19]
## Value Proposition

**As a** user 

**I want to** to add more than one sport to a location

**to be able to** submit all courts available at a location

## Description

![3-17_add multiple sports to location](https://user-images.githubusercontent.com/115343305/211325060-80ac59e9-c729-43c5-89d6-6aee9b94e88d.png)

## Acceptance Criteria

- [ ] form has a "+" - button
- [ ] when the button is clicked another fieldset (sport, number of courts, surface) should appear 
- [ ] data should be stored correctly (see [this user story](https://github.com/marvinRoellecke/capstone-project/issues/11) as reference)
- [ ] user should be allowed to enter max. 10 different sports

## Tasks

(for developers team)

- [ ] add popup window
- [ ] add route to details page
- [ ] create pull request

**Comment by Elgin-Schultz** [comment]
Sounds very convincing to me! Just one minor question: is the storage of the added data part of the user story? When yes, how/where do you store it?
