### ISSUE TITLE
1-1_show list of sport locations

### ISSUE THREAD

**Issue by marvinRoellecke** [marvinRoellecke/capstone-project#2]
## Value Proposition

**As a** user 

**I need** to see a list of sport locations

**to be able to** choose a place where I can do sport

## Description

![10-show list of sport locations](https://user-images.githubusercontent.com/115343305/206899393-99f537dc-e7fe-464f-b4cf-7f0c23542475.png)

## Acceptance Criteria

- [ ] show list of sport locations
- [ ] has header
- [ ] list items should be components

## Tasks

(for developers team)

- [x] create new project with create next-app
- [x] connect project with github
- [x] deploy app on vercel
- [x] clean up folder
- [x] create folder structure (pages, components, images, fonts,...)
- [x] set up global styling (e.g. *box-sizing: border-box)
- [x] create mobile layout in globalStyles
- [x] create dummy array for locations
- [x] create header, main component
- [x] create list item component
- [x] responsive design with grid
- [x] content is scrollable (vertically only)
- [x] render list 
- [x] create pull request
