### ISSUE TITLE
4-19_styling 

### ISSUE THREAD

**Issue by marvinRoellecke** [marvinRoellecke/capstone-project#21]
## Value Proposition

**As a** developer 

**I want** to rework the styling

**to provide a** better user experience.

## Description

n/a

## Acceptance Criteria

- [ ] colors must meet a11y criteria
- [ ] display language must be german  

## Tasks
(for developers team)

- [ ] add css animations
- [ ] import a leaflet map with color (currently b/w)
- [ ] import font locally
- [ ] add subtitle to pages
- [ ] create pull request
