### ISSUE TITLE
1-3_show single page when click on entry

### ISSUE THREAD

**Issue by marvinRoellecke** [marvinRoellecke/capstone-project#4]
## Value Proposition

**As a** user 

**I want to** see a detailed information of sport locations after clicked on list item

**to be able to** get more information about the place where I think about to go to

## Description

![12- show single page when click on entry](https://user-images.githubusercontent.com/115343305/206901193-74dfba70-d278-48c3-8b1d-e4cfd5625a02.png)

## Acceptance Criteria

- [ ] show single page of sport location with more information available
     [image, title, description, rating, address, tags, opening times]
- [ ] use dynamic routing (e.g. [slug].js)
- [ ] page is scrollable in y-direction
- [ ] "go back" -button

## Tasks

(for developers team)

- [ ] update dummy array for locations with more information [...dummyarray, description, opening times]
- [ ] add a "go back" button
- [ ] dummy array is located in lib folder
- [ ] page is aligned into grid
- [ ] create pull request

**Comment by ufelgen** [comment]
Hey Marvin, sieht super aus! vielleicht magst du im Scribble noch zeigen, wo der Back Button hin soll?

**Comment by marvinRoellecke** [comment]
Danke. Guter Punkt, wird gemacht 👍
