### ISSUE TITLE
1-5-add favorite button

### ISSUE THREAD

**Issue by marvinRoellecke** [marvinRoellecke/capstone-project#6]
## Value Proposition

**As a** user 

**I want** to mark an list item as favorite

**to be able to** note places that I visit frequently

## Description

![14-add favorite button](https://user-images.githubusercontent.com/115343305/206919779-c96d9d1a-5794-486e-8c81-053392f77a5f.png)

## Acceptance Criteria

- [ ] favorite button on list item
- [ ] favorite button on details page
- [ ] favorite button is clickable and changes style when checked

## Tasks

(for developers team)

- [ ] add favorite button on list item
- [ ] add favorite button on details page
- [ ] make button a component and use it on list item and details page
- [ ] change style when checked
- [ ] update state when checked
- [ ] create pull request

**Comment by flipkoehler** [comment]
Bin gespannt auf die Funktion! Kannst du noch ein Design anhängen wie der Favoritenbutton auf der Detailspage aussieht?

**Comment by marvinRoellecke** [comment]
Aber natürlich 🤓
