### ISSUE TITLE
2-6-add favorites page and navbar

### ISSUE THREAD

**Issue by marvinRoellecke** [marvinRoellecke/capstone-project#7]
## Value Proposition

**As a** user 

**I want** to see my favorites only

**to be able to** get an overview of places that I visit frequently

## Description

![15-add favorite page and navbar](https://user-images.githubusercontent.com/115343305/206920303-35533de6-4d0d-4279-9ee3-8910ecd5cb13.png)

## Acceptance Criteria

- [ ] show list items marked as favorite on separate page
- [ ] navbar on the bottom
- [ ] home redirects to complete list
- [ ] style of active icon changes

## Tasks

(for developers team)

- [ ] render separate page that show favorite list items only
- [ ] add navbar on bottom
- [ ] create navbar as a component
- [ ] migrate navbar in global styled (mobile layout grid)
- [ ] add button for complete list and favorite list
- [ ] create pull request

**Comment by flipkoehler** [comment]
Hey Marvin, 
schöne Funktion! Vielleicht kannst du noch den Home Button beschreiben, was beim Klick darauf funktioniert und wie sich das Icon verhält. Füllt sich das Icon?

**Comment by marvinRoellecke** [comment]
Danke für den Hinweis Philip, ich passe es an. 👍
